[[redirects]]
  from = "/.well-known/*"
  to = "/not-a-dotfile/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://manual.simtiva.netlify.app/*"
  to = "https://simtiva.netlify.app/manual.html"
  status = 301
  force = true

